// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQATHGLxClcfkQOFW0RZZkyYcB7dPsFA',
    appId: '1:212893502828:web:90e82ea16053840e213749',
    messagingSenderId: '212893502828',
    projectId: 'tfg-7cc22',
    authDomain: 'tfg-7cc22.firebaseapp.com',
    storageBucket: 'tfg-7cc22.appspot.com',
    measurementId: 'G-Z80RYTMVZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9BQdNZ3SrJn1cbOHwY7EgO7VeHauZcNo',
    appId: '1:212893502828:android:50e26b9c19055257213749',
    messagingSenderId: '212893502828',
    projectId: 'tfg-7cc22',
    storageBucket: 'tfg-7cc22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7gpQns1O976BE4eYhhbkynA_XTZq5QSo',
    appId: '1:212893502828:ios:372b3d0a435bfc58213749',
    messagingSenderId: '212893502828',
    projectId: 'tfg-7cc22',
    storageBucket: 'tfg-7cc22.appspot.com',
    iosClientId: '212893502828-gdeoqose946m3hhes666240m61gn9bpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7gpQns1O976BE4eYhhbkynA_XTZq5QSo',
    appId: '1:212893502828:ios:372b3d0a435bfc58213749',
    messagingSenderId: '212893502828',
    projectId: 'tfg-7cc22',
    storageBucket: 'tfg-7cc22.appspot.com',
    iosClientId: '212893502828-gdeoqose946m3hhes666240m61gn9bpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQATHGLxClcfkQOFW0RZZkyYcB7dPsFA',
    appId: '1:212893502828:web:90b6c6bb9d2f7de6213749',
    messagingSenderId: '212893502828',
    projectId: 'tfg-7cc22',
    authDomain: 'tfg-7cc22.firebaseapp.com',
    storageBucket: 'tfg-7cc22.appspot.com',
    measurementId: 'G-0MW94TKNXX',
  );
}
